DROP TABLE IF EXISTS chamado;
DROP TABLE IF EXISTS usuario;

CREATE TABLE usuario (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE chamado (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(150) NOT NULL,
  descricao VARCHAR(225),
  responsavel_id BIGINT NOT NULL,

  FOREIGN KEY (responsavel_id) REFERENCES usuario(id)
);
